---
version: '3.9'
services:
  cache:
    image: azagramac/redis:latest
    container_name: redis
    privileged: true
    network_mode: "host"
    restart: always
    ports:
      - '6379:6379'
    command: sh -c "./redis/init.sh"
    volumes: 
      - cache:/data
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

volumes:
  cache:
    driver: local
