---
services:
  cache:
    image: azagramac/redis:latest
    container_name: redis
    privileged: true
    restart: always
    command: sh -c "./redis/init.sh"
    environment:
      - TZ=Europe/Madrid
    ports:
      - 6379:6379
    volumes: 
      - /volume1/docker/redis:/data:rw
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M

networks:
  redis:
