---
services:
  cache:
    image: azagramac/redis:latest
    container_name: redis
    privileged: true
    restart: always
    command: sh -c "./init.sh"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M

networks:
  redis:
